source 'https://github.com/CocoaPods/Specs.git'

target 'KKCSSLayout', :exclusive => true do
  pod "KKCSSLayout", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "KKCSSLayout", :path => "../"

  
end
