source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'KKCSSLayout', :exclusive => true do
  pod "KKCSSLayout", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "KKCSSLayout", :path => "../"

  
end
